title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://dazz1ee.github.io/FP-wiki

aux_links:
  Lab Repository: https://github.com/MAILabs-Edu-2024/fp-compiler-lab-the-best-team
